jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw clean install --batch-mode -DskipTests=false -Dcheckstyle.skip=false
        -Drat.skip=false -Dmaven.javadoc.skip=true
    - continue-on-error: true
      name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unit
    strategy:
      matrix:
        java:
        - 8
        - 11
    timeout-minutes: 30
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
